### ISSUE TITLE
glib-0.13.12.0 with ghc-9.12.3: ‘runIO_closure’ undeclared

### ISSUE THREAD

**Issue by juhp** [gtk2hs/gtk2hs#348]
glib is failing to rebuild with ghc-9.12.3 for Stackage Nightly somehow:

```
       Building library for glib-0.13.12.0...
       System/Glib/hsgclosure.c: In function ‘gtk2hs_closure_marshal’:
       /home/curators/work/unpack-dir/unpacked/glib-0.13.12.0-c296e1057f0a760c381e2827db2679fad8056b835b2a3e4347c291027d1cf301/System/Glib/hsgclosure.c:111:48: error:
            error: ‘runIO_closure’ undeclared (first use in this function)
             111 |     rts_evalIO(&cap, rts_apply(CAP (HaskellObj)runIO_closure, call),&ret);
                 |                                                ^~~~~~~~~~~~~
           |
       111 |     rts_evalIO(&cap, rts_apply(CAP (HaskellObj)runIO_closure, call),&ret);
           |                                                ^
       
       /home/curators/work/unpack-dir/unpacked/glib-0.13.12.0-c296e1057f0a760c381e2827db2679fad8056b835b2a3e4347c291027d1cf301/System/Glib/hsgclosure.c:111:48: error:
            note: each undeclared identifier is reported only once for each function it appears in
           |
       111 |     rts_evalIO(&cap, rts_apply(CAP (HaskellObj)runIO_closure, call),&ret);
           |                                                ^
       
       `gcc' failed in phase `C Compiler'. (Exit code: 1)
```

Unfortunately this affects 9 dependent packages in Nightly

**Comment by juhp** [comment]
I don't really notice anything directly related in https://downloads.haskell.org/ghc/9.12.3/docs/users_guide/9.12.3-notes.html

**Comment by juhp** [comment]
Seems because of https://gitlab.haskell.org/ghc/ghc/-/merge_requests/14892

cf also https://discourse.haskell.org/t/ghc-9-12-3-is-now-available/13454/5
and https://gitlab.haskell.org/ghc/ghc/-/merge_requests/14892#note_651411

**Comment by TuongNM** [comment]
I've submitted a Pull Request to fix this: #349

**Comment by Aster89** [comment]
[I experience the same with ghc-9.12.4 too.](https://matrix.to/#/!pAORzwKXYKXnnMpVxT:matrix.org/$extbj6fVnOSWBdAhSuQJaPxpmDyazpG9sQNa_FM7aQU?via=matrix.org&via=kf8nh.com&via=tchncs.de)

**Comment by erikd** [comment]
Getting this error with `ghc-9.12.4` on Debian Testing.

Dropping back to `ghc-9.6.7` solved it for me,
