### ISSUE TITLE
gtk2hs-buildtools: Build fails on aarch64-linux due to linker errors

### ISSUE THREAD

**Issue by sternenseemann** [gtk2hs/gtk2hs#305]
```
setupCompilerEnvironmentPhase
Build with /nix/store/mja753gbcdrlngngyb4ag0dr4v52m794-ghc-8.10.4.
unpacking sources
unpacking source archive /nix/store/76h981xv0y0vx8l7g7xc6wydlk3j38p1-gtk2hs-buildtools-0.13.8.0.tar.gz
source root is gtk2hs-buildtools-0.13.8.0
setting SOURCE_DATE_EPOCH to timestamp 1000000000 of file gtk2hs-buildtools-0.13.8.0/src/Gtk2HsSetup.hs
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/setup-package.conf.d -j2 +RTS -A64M -RTS -threaded -rtsopts
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )
Linking Setup ...
updateAutotoolsGnuConfigScriptsPhase
configuring
configureFlags: --verbose --prefix=/nix/store/cwgnfqs2xdbrnw720dspzhsrg3idmi03-gtk2hs-buildtools-0.13.8.0 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --datadir=/nix/store/iw429b56jz0byfyqqrsn1sbx2qwwsslj-gtk2hs-buildtools-0.13.8.0-data/share/ghc-8.10.4 --docdir=/nix/store/k99mlayxvm9qw9s7pf42pmdn82y3ds8r-gtk2hs-buildtools-0.13.8.0-doc/share/doc/gtk2hs-buildtools-0.13.8.0 --with-gcc=gcc --package-db=/build/package.conf.d --ghc-options=-j2 +RTS -A64M -RTS --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --ghc-option=-split-sections --extra-lib-dirs=/nix/store/a9dmvc9yzxfmr0r9g07vfcm4qm259vxr-ncurses-6.2/lib --extra-lib-dirs=/nix/store/psna3vipw1pd0vgcs5bs17skmq46hh1s-libffi-3.3/lib --extra-lib-dirs=/nix/store/bp45qm1sgzbarai4kfr502g42idflsai-gmp-6.2.1/lib
Using Parsec parser
Configuring gtk2hs-buildtools-0.13.8.0...
Flags chosen: closuresignals=True
Dependency Cabal >=1.24.0.0: using Cabal-3.2.1.0
Dependency array -any: using array-0.5.4.0
Dependency base ==4.*: using base-4.14.1.0
Dependency containers >=0.5.5.1: using containers-0.6.2.1
Dependency directory >=1.2.0.0: using directory-1.3.6.0
Dependency filepath >=1.3.0.0: using filepath-1.4.2.1
Dependency hashtables -any: using hashtables-1.2.4.1
Dependency pretty -any: using pretty-1.1.3.6
Dependency process -any: using process-1.6.9.0
Dependency random -any: using random-1.1
Dependency base -any: using base-4.14.1.0
Dependency gtk2hs-buildtools -any: using gtk2hs-buildtools-0.13.8.0
Dependency base -any: using base-4.14.1.0
Dependency gtk2hs-buildtools -any: using gtk2hs-buildtools-0.13.8.0
Dependency base -any: using base-4.14.1.0
Dependency gtk2hs-buildtools -any: using gtk2hs-buildtools-0.13.8.0
Source component graph:
    component lib
    component exe:gtk2hsC2hs dependency lib
    component exe:gtk2hsHookGenerator dependency lib
    component exe:gtk2hsTypeGen dependency lib
Configured component graph:
    component gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
        include Cabal-3.2.1.0
        include array-0.5.4.0
        include base-4.14.1.0
        include containers-0.6.2.1
        include directory-1.3.6.0
        include filepath-1.4.2.1
        include hashtables-1.2.4.1-d2OK6xDB6D2WNIElSzQd8
        include pretty-1.1.3.6
        include process-1.6.9.0
        include random-1.1-IcUwfYF3CGOHS82o6ktbLi
    component gtk2hs-buildtools-0.13.8.0-2ZoVoPCQ6s3GZmbGQ2HxWI-gtk2hsC2hs
        include base-4.14.1.0
        include gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
    component gtk2hs-buildtools-0.13.8.0-K7qvkkRd494BLcRm9LtOtA-gtk2hsHookGenerator
        include base-4.14.1.0
        include gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
    component gtk2hs-buildtools-0.13.8.0-4QLf9P7g8nPKuCbA3L3puK-gtk2hsTypeGen
        include base-4.14.1.0
        include gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
Linked component graph:
    unit gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
        include Cabal-3.2.1.0
        include array-0.5.4.0
        include base-4.14.1.0
        include containers-0.6.2.1
        include directory-1.3.6.0
        include filepath-1.4.2.1
        include hashtables-1.2.4.1-d2OK6xDB6D2WNIElSzQd8
        include pretty-1.1.3.6
        include process-1.6.9.0
        include random-1.1-IcUwfYF3CGOHS82o6ktbLi
        Gtk2HsC2Hs=gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg:Gtk2HsC2Hs,Gtk2HsSetup=gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg:Gtk2HsSetup,HookGenerator=gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg:HookGenerator,TypeGen=gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg:TypeGen
    unit gtk2hs-buildtools-0.13.8.0-2ZoVoPCQ6s3GZmbGQ2HxWI-gtk2hsC2hs
        include base-4.14.1.0
        include gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
    unit gtk2hs-buildtools-0.13.8.0-K7qvkkRd494BLcRm9LtOtA-gtk2hsHookGenerator
        include base-4.14.1.0
        include gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
    unit gtk2hs-buildtools-0.13.8.0-4QLf9P7g8nPKuCbA3L3puK-gtk2hsTypeGen
        include base-4.14.1.0
        include gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
Ready component graph:
    definite gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
        depends Cabal-3.2.1.0
        depends array-0.5.4.0
        depends base-4.14.1.0
        depends containers-0.6.2.1
        depends directory-1.3.6.0
        depends filepath-1.4.2.1
        depends hashtables-1.2.4.1-d2OK6xDB6D2WNIElSzQd8
        depends pretty-1.1.3.6
        depends process-1.6.9.0
        depends random-1.1-IcUwfYF3CGOHS82o6ktbLi
    definite gtk2hs-buildtools-0.13.8.0-K7qvkkRd494BLcRm9LtOtA-gtk2hsHookGenerator
        depends base-4.14.1.0
        depends gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
    definite gtk2hs-buildtools-0.13.8.0-4QLf9P7g8nPKuCbA3L3puK-gtk2hsTypeGen
        depends base-4.14.1.0
        depends gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
    definite gtk2hs-buildtools-0.13.8.0-2ZoVoPCQ6s3GZmbGQ2HxWI-gtk2hsC2hs
        depends base-4.14.1.0
        depends gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
Using Cabal-3.2.1.0 compiled by ghc-8.10
Using compiler: ghc-8.10.4
Using install prefix:
/nix/store/cwgnfqs2xdbrnw720dspzhsrg3idmi03-gtk2hs-buildtools-0.13.8.0
Executables installed in:
/nix/store/cwgnfqs2xdbrnw720dspzhsrg3idmi03-gtk2hs-buildtools-0.13.8.0/bin
Libraries installed in:
/nix/store/cwgnfqs2xdbrnw720dspzhsrg3idmi03-gtk2hs-buildtools-0.13.8.0/lib/ghc-8.10.4/aarch64-linux-ghc-8.10.4/gtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg
Dynamic Libraries installed in:
/nix/store/cwgnfqs2xdbrnw720dspzhsrg3idmi03-gtk2hs-buildtools-0.13.8.0/lib/ghc-8.10.4/aarch64-linux-ghc-8.10.4
Private executables installed in:
/nix/store/cwgnfqs2xdbrnw720dspzhsrg3idmi03-gtk2hs-buildtools-0.13.8.0/libexec/aarch64-linux-ghc-8.10.4/gtk2hs-buildtools-0.13.8.0
Data files installed in:
/nix/store/iw429b56jz0byfyqqrsn1sbx2qwwsslj-gtk2hs-buildtools-0.13.8.0-data/share/ghc-8.10.4/aarch64-linux-ghc-8.10.4/gtk2hs-buildtools-0.13.8.0
Documentation installed in:
/nix/store/k99mlayxvm9qw9s7pf42pmdn82y3ds8r-gtk2hs-buildtools-0.13.8.0-doc/share/doc/gtk2hs-buildtools-0.13.8.0
Configuration files installed in:
/nix/store/cwgnfqs2xdbrnw720dspzhsrg3idmi03-gtk2hs-buildtools-0.13.8.0/etc
Using alex version 3.2.6 found on system at:
/nix/store/7gifll6as161f5cyh5ja8fnml7b9sv3f-alex-3.2.6/bin/alex
Using ar found on system at:
/nix/store/5x1fxv6qpr77biajn2vyj733c7frr35x-binutils-2.35.1/bin/ar
No c2hs found
No cpphs found
No doctest found
Using gcc version 9.3.0 given by user at:
/nix/store/77rbb5wkbd7di015si690mzny3w148h2-gcc-wrapper-9.3.0/bin/gcc
Using ghc version 8.10.4 found on system at:
/nix/store/mja753gbcdrlngngyb4ag0dr4v52m794-ghc-8.10.4/bin/ghc
Using ghc-pkg version 8.10.4 found on system at:
/nix/store/mja753gbcdrlngngyb4ag0dr4v52m794-ghc-8.10.4/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.24.0 found on system at:
/nix/store/mja753gbcdrlngngyb4ag0dr4v52m794-ghc-8.10.4/bin/haddock
Using happy version 1.20.0 found on system at:
/nix/store/5in76xyd4c858qmz63d1n462lwfspjyz-happy-1.20.0/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.68 found on system at:
/nix/store/mja753gbcdrlngngyb4ag0dr4v52m794-ghc-8.10.4/bin/hpc
Using hsc2hs version 0.68.7 found on system at:
/nix/store/mja753gbcdrlngngyb4ag0dr4v52m794-ghc-8.10.4/bin/hsc2hs
Using hscolour version 1.24 found on system at:
/nix/store/p55z1rsa1aj0lqpfsmqsh49qwxpk2hm4-hscolour-1.24.4/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/1ky4k68w967zp083kkjviir1h2y8xh4c-binutils-wrapper-2.35.1/bin/ld.gold
No pkg-config found
Using runghc version 8.10.4 found on system at:
/nix/store/mja753gbcdrlngngyb4ag0dr4v52m794-ghc-8.10.4/bin/runghc
Using strip version 2.35 found on system at:
/nix/store/5x1fxv6qpr77biajn2vyj733c7frr35x-binutils-2.35.1/bin/strip
Using tar found on system at:
/nix/store/d3mjngrf7nn0zcriiw2d714gga808ign-gnutar-1.34/bin/tar
No uhc found
building
Preprocessing library for gtk2hs-buildtools-0.13.8.0..
Building library for gtk2hs-buildtools-0.13.8.0..
[ 1 of 46] Compiling BaseVersion      ( c2hs/base/admin/BaseVersion.hs, dist/build/BaseVersion.o, dist/build/BaseVersion.dyn_o )
[ 2 of 46] Compiling C2HSConfig       ( c2hs/toplevel/C2HSConfig.hs, dist/build/C2HSConfig.o, dist/build/C2HSConfig.dyn_o )
[ 3 of 46] Compiling CInfo            ( c2hs/gen/CInfo.hs, dist/build/CInfo.o, dist/build/CInfo.dyn_o )
[ 4 of 46] Compiling Config           ( c2hs/base/admin/Config.hs, dist/build/Config.o, dist/build/Config.dyn_o )
[ 5 of 46] Compiling DLists           ( c2hs/base/general/DLists.hs, dist/build/DLists.o, dist/build/DLists.dyn_o )
[ 6 of 46] Compiling FNameOps         ( c2hs/base/general/FNameOps.hs, dist/build/FNameOps.o, dist/build/FNameOps.dyn_o )
[ 7 of 46] Compiling FastMutInt       ( c2hs/base/general/FastMutInt.hs, dist/build/FastMutInt.o, dist/build/FastMutInt.dyn_o )
[ 8 of 46] Compiling FileOps          ( c2hs/base/general/FileOps.hs, dist/build/FileOps.o, dist/build/FileOps.dyn_o )
[ 9 of 46] Compiling Map              ( c2hs/base/general/Map.hs, dist/build/Map.o, dist/build/Map.dyn_o )
[10 of 46] Compiling Binary           ( c2hs/base/general/Binary.hs, dist/build/Binary.o, dist/build/Binary.dyn_o )
[11 of 46] Compiling Paths_gtk2hs_buildtools ( dist/build/autogen/Paths_gtk2hs_buildtools.hs, dist/build/Paths_gtk2hs_buildtools.o, dist/build/Paths_gtk2hs_buildtools.dyn_o )
[12 of 46] Compiling HookGenerator    ( callbackGen/HookGenerator.hs, dist/build/HookGenerator.o, dist/build/HookGenerator.dyn_o )
[13 of 46] Compiling Position         ( c2hs/base/general/Position.hs, dist/build/Position.o, dist/build/Position.dyn_o )
[14 of 46] Compiling Errors           ( c2hs/base/errors/Errors.hs, dist/build/Errors.o, dist/build/Errors.dyn_o )
[15 of 46] Compiling Lexers           ( c2hs/base/syntax/Lexers.hs, dist/build/Lexers.o, dist/build/Lexers.dyn_o )

c2hs/base/syntax/Lexers.hs:133:1: warning: [-Wtabs]
    Tab character found here, and in 172 further locations.
    Please use spaces instead.
    |
133 |                lexactionErr, lexmeta, (>|<), (>||<), ctrlChars, ctrlLexer,
    | ^^^^^^^^
[16 of 46] Compiling Set              ( c2hs/base/general/Set.hs, dist/build/Set.o, dist/build/Set.dyn_o )
[17 of 46] Compiling StateTrans       ( c2hs/base/state/StateTrans.hs, dist/build/StateTrans.o, dist/build/StateTrans.dyn_o )
[18 of 46] Compiling Switches         ( c2hs/state/Switches.hs, dist/build/Switches.o, dist/build/Switches.dyn_o )
[19 of 46] Compiling TypeGen          ( hierarchyGen/TypeGen.hs, dist/build/TypeGen.o, dist/build/TypeGen.dyn_o )
[20 of 46] Compiling UNames           ( c2hs/base/general/UNames.hs, dist/build/UNames.o, dist/build/UNames.dyn_o )
[21 of 46] Compiling StateBase        ( c2hs/base/state/StateBase.hs, dist/build/StateBase.o, dist/build/StateBase.dyn_o )
[22 of 46] Compiling CIO              ( c2hs/base/state/CIO.hs, dist/build/CIO.o, dist/build/CIO.dyn_o )

c2hs/base/state/CIO.hs:77:1: warning: [-Wdeprecations]
    Module ‘System.Cmd’ is deprecated: Use "System.Process" instead
   |
77 | import System.Cmd
   | ^^^^^^^^^^^^^^^^^
[23 of 46] Compiling State            ( c2hs/base/state/State.hs, dist/build/State.o, dist/build/State.dyn_o )
[24 of 46] Compiling C2HSState        ( c2hs/state/C2HSState.hs, dist/build/C2HSState.o, dist/build/C2HSState.dyn_o )
[25 of 46] Compiling Attributes       ( c2hs/base/syms/Attributes.hs, dist/build/Attributes.o, dist/build/Attributes.dyn_o )
[26 of 46] Compiling Idents           ( c2hs/base/syms/Idents.hs, dist/build/Idents.o, dist/build/Idents.dyn_o )
[27 of 46] Compiling NameSpaces       ( c2hs/base/syms/NameSpaces.hs, dist/build/NameSpaces.o, dist/build/NameSpaces.dyn_o )
[28 of 46] Compiling CTokens          ( c2hs/c/CTokens.hs, dist/build/CTokens.o, dist/build/CTokens.dyn_o )
[29 of 46] Compiling CParserMonad     ( c2hs/c/CParserMonad.hs, dist/build/CParserMonad.o, dist/build/CParserMonad.dyn_o )
[30 of 46] Compiling CLexer           ( dist/build/CLexer.hs, dist/build/CLexer.o, dist/build/CLexer.dyn_o )

c2hs/c/CLexer.x:75:14: warning: [-Wtabs]
    Tab character found here, and in 226 further locations.
    Please use spaces instead.
   |
75 | import UNames    (Name)
   |              ^^^
[31 of 46] Compiling CHSLexer         ( c2hs/chs/CHSLexer.hs, dist/build/CHSLexer.o, dist/build/CHSLexer.dyn_o )
[32 of 46] Compiling CHS              ( c2hs/chs/CHS.hs, dist/build/CHS.o, dist/build/CHS.dyn_o )
[33 of 46] Compiling GenHeader        ( c2hs/gen/GenHeader.hs, dist/build/GenHeader.o, dist/build/GenHeader.dyn_o )
[34 of 46] Compiling CAST             ( c2hs/c/CAST.hs, dist/build/CAST.o, dist/build/CAST.dyn_o )
[35 of 46] Compiling CPretty          ( c2hs/c/CPretty.hs, dist/build/CPretty.o, dist/build/CPretty.dyn_o )
[36 of 46] Compiling CAttrs           ( c2hs/c/CAttrs.hs, dist/build/CAttrs.o, dist/build/CAttrs.dyn_o )
[37 of 46] Compiling CTrav            ( c2hs/c/CTrav.hs, dist/build/CTrav.o, dist/build/CTrav.dyn_o )
[38 of 46] Compiling CBuiltin         ( c2hs/c/CBuiltin.hs, dist/build/CBuiltin.o, dist/build/CBuiltin.dyn_o )
[39 of 46] Compiling CParser          ( dist/build/CParser.hs, dist/build/CParser.o, dist/build/CParser.dyn_o )
[40 of 46] Compiling CNames           ( c2hs/c/CNames.hs, dist/build/CNames.o, dist/build/CNames.dyn_o )
[41 of 46] Compiling C                ( c2hs/c/C.hs, dist/build/C.o, dist/build/C.dyn_o )
[42 of 46] Compiling GBMonad          ( c2hs/gen/GBMonad.hs, dist/build/GBMonad.o, dist/build/GBMonad.dyn_o )
[43 of 46] Compiling GenBind          ( c2hs/gen/GenBind.hs, dist/build/GenBind.o, dist/build/GenBind.dyn_o )
[44 of 46] Compiling Version          ( c2hs/toplevel/Version.hs, dist/build/Version.o, dist/build/Version.dyn_o )
[45 of 46] Compiling Gtk2HsC2Hs       ( c2hs/toplevel/Gtk2HsC2Hs.hs, dist/build/Gtk2HsC2Hs.o, dist/build/Gtk2HsC2Hs.dyn_o )
[46 of 46] Compiling Gtk2HsSetup      ( src/Gtk2HsSetup.hs, dist/build/Gtk2HsSetup.o, dist/build/Gtk2HsSetup.dyn_o )
Preprocessing executable 'gtk2hsHookGenerator' for gtk2hs-buildtools-0.13.8.0..
Building executable 'gtk2hsHookGenerator' for gtk2hs-buildtools-0.13.8.0..
[1 of 1] Compiling Main             ( exe/gtk2hsHookGeneratorMain.hs, dist/build/gtk2hsHookGenerator/gtk2hsHookGenerator-tmp/Main.o )
Linking dist/build/gtk2hsHookGenerator/gtk2hsHookGenerator ...
Preprocessing executable 'gtk2hsTypeGen' for gtk2hs-buildtools-0.13.8.0..
Building executable 'gtk2hsTypeGen' for gtk2hs-buildtools-0.13.8.0..
[1 of 1] Compiling Main             ( exe/gtk2hsTypeGenMain.hs, dist/build/gtk2hsTypeGen/gtk2hsTypeGen-tmp/Main.o )
Linking dist/build/gtk2hsTypeGen/gtk2hsTypeGen ...
Preprocessing executable 'gtk2hsC2hs' for gtk2hs-buildtools-0.13.8.0..
Building executable 'gtk2hsC2hs' for gtk2hs-buildtools-0.13.8.0..
[1 of 1] Compiling Main             ( exe/gtk2hsC2hsMain.hs, dist/build/gtk2hsC2hs/gtk2hsC2hs-tmp/Main.o )
Linking dist/build/gtk2hsC2hs/gtk2hsC2hs ...
/build/gtk2hs-buildtools-0.13.8.0/dist/build/libHSgtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg.a(Binary.o)(.text.gtk2hszmbuildtoolszm0zi13zi8zi0zm5EWuT5LwZZ1eDBrXNttWOYg_Binary_zdfBinaryInteger4_info+0x0): error: undefined reference to 'cAGx_closure'
/build/gtk2hs-buildtools-0.13.8.0/dist/build/libHSgtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg.a(Binary.o)(.text.cABA_info+0x0): error: undefined reference to 'cAGP_closure'
/build/gtk2hs-buildtools-0.13.8.0/dist/build/libHSgtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg.a(Binary.o)(.text.cABC_info+0x0): error: undefined reference to 'cAGP_closure'
/build/gtk2hs-buildtools-0.13.8.0/dist/build/libHSgtk2hs-buildtools-0.13.8.0-5EWuT5LwZ1eDBrXNttWOYg.a(Binary.o):ghc_179.ll:_uAIi_srt$def: error: undefined reference to 'cAGP_closure'
collect2: error: ld returned 1 exit status
`cc' failed in phase `Linker'. (Exit code: 1)
builder for '/nix/store/cyjxjcraalmp54jxkikmjwl77iw80z3b-gtk2hs-buildtools-0.13.8.0.drv' failed with exit code 1
```

* `cc` is GCC 9.3.0
* `ld` is from binutils 2.35.1

**Comment by juhp** [comment]
I am hitting this too for Fedora aarch64:

Fedora Rawhide F35 build on aarch64:
https://koji.fedoraproject.org/koji/taskinfo?taskID=73396429 (full logs available for 2 weeks)
```
[46 of 46] Compiling Gtk2HsSetup      ( src/Gtk2HsSetup.hs, dist/build/Gtk2HsSetup.p_o )
Preprocessing executable 'gtk2hsTypeGen' for gtk2hs-buildtools-0.13.8.0..
Building executable 'gtk2hsTypeGen' for gtk2hs-buildtools-0.13.8.0..
[1 of 1] Compiling Main             ( exe/gtk2hsTypeGenMain.hs, dist/build/gtk2hsTypeGen/gtk2hsTypeGen-tmp/Main.o )
Linking dist/build/gtk2hsTypeGen/gtk2hsTypeGen ...
Preprocessing executable 'gtk2hsC2hs' for gtk2hs-buildtools-0.13.8.0..
Building executable 'gtk2hsC2hs' for gtk2hs-buildtools-0.13.8.0..
[1 of 1] Compiling Main             ( exe/gtk2hsC2hsMain.hs, dist/build/gtk2hsC2hs/gtk2hsC2hs-tmp/Main.o )
Linking dist/build/gtk2hsC2hs/gtk2hsC2hs ...
/builddir/build/BUILD/gtk2hs-buildtools-0.13.8.0/dist/build/libHSgtk2hs-buildtools-0.13.8.0-JOwoEYMToCk3CRhTExgw6U.a(Binary.o)(.text+0xde28): error: undefined reference to 'ct5j_closure'
/builddir/build/BUILD/gtk2hs-buildtools-0.13.8.0/dist/build/libHSgtk2hs-buildtools-0.13.8.0-JOwoEYMToCk3CRhTExgw6U.a(Binary.o)(.text+0xdf28): error: undefined reference to 'ct5B_closure'
/builddir/build/BUILD/gtk2hs-buildtools-0.13.8.0/dist/build/libHSgtk2hs-buildtools-0.13.8.0-JOwoEYMToCk3CRhTExgw6U.a(Binary.o)(.text+0xdf68): error: undefined reference to 'ct5B_closure'
/builddir/build/BUILD/gtk2hs-buildtools-0.13.8.0/dist/build/libHSgtk2hs-buildtools-0.13.8.0-JOwoEYMToCk3CRhTExgw6U.a(Binary.o):ghc_135.ll:_ut6H_srt$def: error: undefined reference to 'ct5B_closure'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```

**Comment by sternenseemann** [comment]
The workaround mentioned in the GHC thread works as well for aarch64, compiling with `-O0` works (didn't try LLVM properly which is also suggested). Seems like this is probably a GHC bug in some shape or form, but not sure why gtk2hs-buildtools is hitting it…

**Comment by juhp** [comment]
Thank you will try that.

Also I note that it builds fine on aarch64 with ghc-8.8.4 (using llvm).

**Comment by juhp** [comment]
Thank you!  Indeed -O0 works for aarch64 with ghc-8.10.5.

**Comment by hamishmack** [comment]
Please try this workaround ce06bb7f79fc2fe8b259486032e602b1816bebcd.  It seems to work for me, so I have uploaded it to hackage as [gtk2hs-buildtools-0.13.8.2](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.8.2).

**Comment by juhp** [comment]
Thanks Hamish! - I tested building on Fedora Rawhide now and it succeeded now on all archs without any tweaks. :+1: 
https://koji.fedoraproject.org/koji/taskinfo?taskID=78138593

**Comment by sternenseemann** [comment]
Can't reproduce it anymore as well, at least on aarch64.
