### ISSUE TITLE
gtk2hs-buildtools doesn't build on ghc 8.2.1-rc2 with --allow-newer

### ISSUE THREAD

**Issue by GeorgeCo** [gtk2hs/gtk2hs#203]
Not sure if the following is a known issue
gtk2hs-buildtools doesn't build on ghc 8.2.1-rc2:
 cabal install gtk2hs-buildtools-0.13.2.2 --allow-newer
...
[46 of 46] Compiling Gtk2HsSetup      ( src/Gtk2HsSetup.hs, dist/build/Gtk2HsSetup.o )

src/Gtk2HsSetup.hs:75:61: error:
    Not in scope: ‘LBI.componentsConfigs’
    Module ‘Distribution.Simple.LocalBuildInfo’ does not export ‘componentsConfigs’.
   |
75 | libraryConfig lbi = case [clbi | (LBI.CLibName, clbi, _) <- LBI.componentsConfigs lbi] of
   |                                                             ^^^^^^^^^^^^^^^^^^^^^

src/Gtk2HsSetup.hs:311:44: error:
    Not in scope: data constructor ‘Version’
    Perhaps you meant one of these:
      variable ‘mkVersion’ (imported from Distribution.Simple),
      variable ‘noVersion’ (imported from Distribution.Simple)
    |
311 |                  | PackageIdentifier name (Version (major:minor:_) _) <- cPkgs
    |                                            ^^^^^^^
cabal: Leaving directory '/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-83597/gtk2hs-buildtools-0.13.2.2'
cabal: Error: some packages failed to install:
gtk2hs-buildtools-0.13.2.2 failed during the building phase. The exception
was:
ExitFailure 1

**Comment by mrkgnao** [comment]
Now that Stackage Nightly supports ghc-8.2.1, more people are going to report this. I'm facing the same error.

**Comment by GeorgeCo** [comment]
It's working now for me if I do: cabal install -fhave-quartz-gtk gtk

**Comment by deepfire** [comment]
Same error on Linux.

**Comment by hamishmack** [comment]
I think this has been fixed.
