### ISSUE TITLE
gtk2hs-buildtools fails to build on ppc64le with ghc-8.6.5

### ISSUE THREAD

**Issue by juhp** [gtk2hs/gtk2hs#279]
Not really sure why but gtk2hs-buildtools-0.13.[45] fails to build on ppc64le with ghc-8.6.5.
See also the Fedora bug https://bugzilla.redhat.com/show_bug.cgi?id=1737587:

```
Building executable 'gtk2hsC2hs' for gtk2hs-buildtools-0.13.5.0..
[1 of 1] Compiling Main             ( exe/gtk2hsC2hsMain.hs, dist/build/gtk2hsC2hs/gtk2hsC2hs-tmp/Main.o )
Linking dist/build/gtk2hsC2hs/gtk2hsC2hs ...
BUILDSTDERR: /builddir/build/BUILD/gtk2hs-buildtools-0.13.5.0/dist/build/libHSgtk2hs-buildtools-0.13.5.0-KQlf14Qb9I4Aj3qfo8QuZi.a(Binary.o)(.data+0x1798): error: undefined reference to 'crcF_closure'
BUILDSTDERR: /builddir/build/BUILD/gtk2hs-buildtools-0.13.5.0/dist/build/libHSgtk2hs-buildtools-0.13.5.0-KQlf14Qb9I4Aj3qfo8QuZi.a(Binary.o)(.data.rel.ro+0x4720): error: undefined reference to 'crcF_closure'
BUILDSTDERR: /builddir/build/BUILD/gtk2hs-buildtools-0.13.5.0/dist/build/libHSgtk2hs-buildtools-0.13.5.0-KQlf14Qb9I4Aj3qfo8QuZi.a(Binary.o)(.data.rel.ro+0x4740): error: undefined reference to 'crcF_closure'
BUILDSTDERR: /builddir/build/BUILD/gtk2hs-buildtools-0.13.5.0/dist/build/libHSgtk2hs-buildtools-0.13.5.0-KQlf14Qb9I4Aj3qfo8QuZi.a(Binary.o)(.data.rel.ro+0x4760): error: undefined reference to 'crcF_closure'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: `gcc' failed in phase `Linker'. (Exit code: 1)
```
Since it builds okay with ghc-8.4.4 perhaps this is a ghc issue.

**Comment by juhp** [comment]
I reported this also to ghc upstream: https://gitlab.haskell.org/ghc/ghc/issues/17203

**Comment by sternenseemann** [comment]
Something similar happens on aarch64-linux as well: https://github.com/gtk2hs/gtk2hs/issues/305
