### ISSUE TITLE
gtkhs-buildtools-0.13.10.0 (latest) fails to build with Cabal-3.12

### ISSUE THREAD

**Issue by andreasabel** [gtk2hs/gtk2hs#334]
```
src/Gtk2HsSetup.hs:33:44: error: [GHC-10237]
    In the import of ‘Distribution.Simple.LocalBuildInfo’:
      an item called ‘LocalBuildInfo’ is exported, but it does not export any children
      (constructors, class methods or field names) called ‘buildDir’.
   |
33 | import Distribution.Simple.LocalBuildInfo (LocalBuildInfo(withPackageDB, buildDir, localPkgDescr, installedPkgs, withPrograms),
   |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: [Cabal-7125]
Failed to build gtk2hs-buildtools-0.13.10.0 
```
I mitigated the problem via revisions enforcing `Cabal < 3.11`, but a fix needs code changes and a rerelease:

2024-07-01T04:43:52Z  	AndreasAbel	  [gtk2hs-buildtools-0.13.8.2-r2](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.8.2/revisions)
2024-07-01T04:43:51Z  	AndreasAbel	  [gtk2hs-buildtools-0.13.8.1-r2](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.8.1/revisions)
2024-07-01T04:43:48Z  	AndreasAbel	  [gtk2hs-buildtools-0.13.8.0-r2](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.8.0/revisions)
2024-07-01T04:43:48Z  	AndreasAbel	  [gtk2hs-buildtools-0.13.5.4-r1](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.5.4/revisions)
2024-07-01T04:43:45Z  	AndreasAbel	  [gtk2hs-buildtools-0.13.5.3-r1](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.5.3/revisions)
2024-07-01T04:43:44Z  	AndreasAbel	  [gtk2hs-buildtools-0.13.5.1-r1](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.5.1/revisions)
2024-07-01T04:43:34Z  	AndreasAbel	  [gtk2hs-buildtools-0.13.10.0-r2](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.10.0/revisions)

**Comment by hamishmack** [comment]
This has been fixed and uploaded to hackage.
