### PR TITLE
Fix glib for RTS API change in GHC 9.12.3/9.14.1

### LINKED ISSUE #348: glib-0.13.12.0 with ghc-9.12.3: ‘runIO_closure’ undeclared
glib is failing to rebuild with ghc-9.12.3 for Stackage Nightly somehow:

```
       Building library for glib-0.13.12.0...
       System/Glib/hsgclosure.c: In function ‘gtk2hs_closure_marshal’:
       /home/curators/work/unpack-dir/unpacked/glib-0.13.12.0-c296e1057f0a760c381e2827db2679fad8056b835b2a3e4347c291027d1cf301/System/Glib/hsgclosure.c:111:48: error:
            error: ‘runIO_closure’ undeclared (first use in this function)
             111 |     rts_evalIO(&cap, rts_apply(CAP (HaskellObj)runIO_closure, call),&ret);
                 |                                                ^~~~~~~~~~~~~
           |
       111 |     rts_evalIO(&cap, rts_apply(CAP (HaskellObj)runIO_closure, call),&ret);
           |                                                ^
       
       /home/curators/work/unpack-dir/unpacked/glib-0.13.12.0-c296e1057f0a760c381e2827db2679fad8056b835b2a3e4347c291027d1cf301/System/Glib/hsgclosure.c:111:48: error:
            note: each undeclared identifier is reported only once for each function it appears in
           |
       111 |     rts_evalIO(&cap, rts_apply(CAP (HaskellObj)runIO_closure, call),&ret);
           |                                                ^
       
       `gcc' failed in phase `C Compiler'. (Exit code: 1)
```

Unfortunately this affects 9 dependent packages in Nightly

### PR DESCRIPTION
**Pull request by TuongNM**
Fixes #348

I updated the CI and cabal files to show that it builds with GHC 9.14.1. If you don't want me to mess with these files, I can remove those changes again.

Since GHC 9.12.3 is not in ghcup due to [https://gitlab.haskell.org/ghc/ghc/-/issues/26711](https://gitlab.haskell.org/ghc/ghc/-/issues/26711), I did a `stack build` with the following `stack.yaml` to check that it builds:

```
snapshot: nightly-2026-02-14

packages:
- cairo
- gio
- glib
- gtk
- pango
- tools
```

### CODE REVIEW

**Comment by TuongNM** [comment]
@hamishmack Could you take a look at this, please?

**Comment by Aster89** [comment]
[GHC 9.12.4 is affected too](https://matrix.to/#/!pAORzwKXYKXnnMpVxT:matrix.org/$extbj6fVnOSWBdAhSuQJaPxpmDyazpG9sQNa_FM7aQU?via=matrix.org&via=kf8nh.com&via=tchncs.de).

**Comment by turboMaCk** [comment]
:+1: for merge :pray:

**Comment by TeofilC** [comment]
Gentle ping @hamishmack

**Comment by ratherforky** [comment]
Gently pinging @hamishmack again. This is still an issue for GHC 9.14.1 which is causing upstream build failures (in my case, xmobar).
