### ISSUE TITLE
gtk2hs-buildtools fails to build with cabal 3.14

### ISSUE THREAD

**Issue by GuillaumedeVolpiano** [gtk2hs/gtk2hs#338]
There has been an API change in Distribution.Simple.Setup in Cabal 3.14. CopyFlags now only has two fields, copyCommonFlags and copyDests, and, if my understanding is correct, copyDistPref is now setupDistPref, a field of copyCommonFlags. Because of this, compilation of Gtk2HsC2Hs fails with ghc-9.12/Cabal 3.14

src/Gtk2HsSetup.hs:180:19: error: [GHC-14392]
    Invalid record update.
    No constructor in scope has all of the following fields:
      ‘copyDistPref’, ‘copyDest’
    |
180 |   let copyFlags = defaultCopyFlags {
